### ISSUE TITLE
Swap the order

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/stargazed#12]
To make it look like

sl. No | Name | Description | Author | Stars

**Comment by lindgr3n** [comment]
I can help on this :)

**Comment by abhijithvijayan** [comment]
@lindgr3n make sure you use a text-editor like gedit instead of vscode.

VScode might auto lint and breaks the template as it is.

**Comment by lindgr3n** [comment]
Good to know 👍
