### ISSUE TITLE
some content hrefs are buggy

### ISSUE THREAD

**Issue by phanirithvij** [abhijithvijayan/stargazed#2]
Try
```
stargazed -u "phanirithvij"
```
`- [DIGITAL&nbsp;Command Language](#digital-command language)` is the output
The expected output should be

`- [DIGITAL Command Language](#digital-command-language)`

**Comment by abhijithvijayan** [comment]
working on it.

**Comment by abhijithvijayan** [comment]
Fixed and released new version

Update with

`npm i -g stargazed@latest`
