### ISSUE TITLE
Pipe chars don't get escaped (breaking markdown table)

### ISSUE THREAD

**Issue by vintagesucks** [abhijithvijayan/stargazed#23]
## Checklist
- [x] I checked that this is not an existing issue
- [x] I gave clear steps to reproduce this issue
- [x] I formatted all code samples correctly (if relevant)

## Expected Behavior
The pipe (|) gets escaped.

## Current Behavior
The pipe (|) is not escaped, breaking the markdown of the table row.

## Possible Solution
Escape the pipe

## Steps to Reproduce
[Live example](https://github.com/vintagesucks/awesome-stars/blob/master/README.md#php) (anti-xss):

![grafik](https://user-images.githubusercontent.com/13335308/66815518-b0819480-ef38-11e9-8020-be930fb54e23.png)

## Context
Original description of voku/anti-xss:

![grafik](https://user-images.githubusercontent.com/13335308/66816962-41f20600-ef3b-11e9-8537-2da0a2f07c02.png)

## Detailed Description
Escape the pipe (|) to prevent it from breaking the markdown.

**Comment by abhijithvijayan** [comment]
@vintagesucks If you could submit a PR for this issue, that would be great.

**Comment by vintagesucks** [comment]
@abhijithvijayan No problem, I'll do that later today.

**Comment by abhijithvijayan** [comment]
@vintagesucks 

`node cli.js -u "abhijithvijayan" -t "TOKEN"`

**Comment by vintagesucks** [comment]
@abhijithvijayan Thanks! Yeah, #25 is what I was struggling with.
