### ISSUE TITLE
Use babel npm package to transpile your ES6 to a commonjs target

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/stargazed#25]
export const validate = _options => {
^^^^^^

SyntaxError: Unexpected token export

**Comment by abhijithvijayan** [comment]
See https://github.com/abhijithvijayan/stargazed/issues/19#issuecomment-542835156

**Comment by abhijithvijayan** [comment]
The error occurs on running
`node cli.js -u "abhijithvijayan"

The module.exports doesn't seem to cooporate with importing in tests/index.test.js

**Comment by abhijithvijayan** [comment]
### Possible fix:



In index.js
```
module.exports.foo = foo;
// default import
module.exports = bar;
```

Then import in another file

```
import fooBar from './';

fooBar();
fooBar.foo();
1. ```

**Comment by JacobMGEvans** [comment]
You could probably just implement babel-node and use newer JavaScript features, though Node should be supporting these by now what version of Node is this running on?

**Comment by abhijithvijayan** [comment]
@JacobMGEvans v10 LTS

Though it seems to be using babel-node a better idea, CLI works good for now, hence, unless required, we could stay using the Node.js features.

If you run into somekinda error writing tests or if yoi feel like using some advanced features, feel free to submit a PR with babel-node addition.

**Comment by JacobMGEvans** [comment]
Awesome! Will do, thanks. I'll focus on the unit tests first 😆
