### ISSUE TITLE
replace npm badge with travis status badge

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/stargazed#35]
Use
`
[![Build Status](https://travis-ci.com/abhijithvijayan/stargazed.svg?branch=master)](https://travis-ci.com/abhijithvijayan/stargazed)
`

**Comment by fernandomaia** [comment]
Can I take this one @abhijithvijayan?

**Comment by HarisSpahija** [comment]
Pull request created. Can this be reviewed?

**Comment by abhijithvijayan** [comment]
> Can I take this one @abhijithvijayan?

#36
