### ISSUE TITLE
Disable linting the markdown file (template.md)

### ISSUE THREAD

**Issue by abhijithvijayan** [abhijithvijayan/stargazed#38]
The markdown linter, applies linting automatically on the `template.md` file when applied a change and saved.

The VScode I use, really messes this up and output produced by CLI is then ruined.

If there is any config that disables this auto lint, it might be useful.

**Comment by Bhavesh27** [comment]
let me work on it

**Comment by Bhavesh27** [comment]
Added .markdownlint.ignore file to disable markdown linting
https://github.com/abhijithvijayan/stargazed/pull/39

**Comment by abhijithvijayan** [comment]
> Added .markdownlint.ignore file to disable markdown linting
> #39

This doesn't work

**Comment by Bhavesh27** [comment]
can you share vscode extension(name, Author) you are using maybe it supports .ignore file in different format.

**Comment by abhijithvijayan** [comment]
https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

**Comment by Bhavesh27** [comment]
working on it.

**Comment by Bhavesh27** [comment]
Hope it helps.

**Comment by abhijithvijayan** [comment]
I will verify it and close this issue afterwards. Thanks for the PR.

**Comment by abhijithvijayan** [comment]
I have no idea why even after this commit, my text editor formatting the file again.

I am gonna close this issue now, and I will work on the configuration if that's a local issue with VSCode
