### ISSUE TITLE
GitHub Action documentation

### ISSUE THREAD

**Issue by almereyda** [abhijithvijayan/stargazed#52]
## Checklist
- [x] I checked that this is not an existing issue
- [x] I gave clear steps to reproduce this issue
- [x] I formatted all code samples correctly (if relevant)

## Expected Behavior

A command like

    stargazed --username almereyda --token of_sorts --sort --repository awesome-stars -w

sets up a GitHub repository, if not existing, and Action for updating the repository.

## Current Behavior

1. Running the command without the repository existing does not create it with an initial commit and does not set the GitHub Action.
2. Running the command for a manually created repository does not create a commit and does not create a visible action in https://github.com/almereyda/awesome-stars/actions/new

## Possible Solution

`stargazed` is able to fetch the repository's configuration If the repository does not yet exist, it is being created and set up with an initial commit plus GitHub Action. (Note the `-w` flag.)

## Steps to Reproduce

1. Run the `stargazed` command above with your username and your personal access token.
2. Review the GitHub Actions

## Context (Environment)

This is a Fedora 30, Node 10 environment.

## Possible Implementation

It could be nice to have a CLI flag that can read the repository configuration and update on the status of an eventual integration.

**Comment by abhijithvijayan** [comment]
Let me see if I can reproduce this error

**Comment by abhijithvijayan** [comment]
@almereyda This is not a bug as the --repository flag doesn't exist. which is --repo instead.

**Comment by abhijithvijayan** [comment]
I can't change `--repo` as this will cause breaking changes to all those users who have set up workflow.

Maybe I will alias it so as to accept both `--repo` and `--repository` flags

**Comment by abhijithvijayan** [comment]
Have aliased `--repository` flag

Use `npx` to use the latest version of CLI

I am closing this for now.

If you still have issue, feel free to reopen this.

**Comment by almereyda** [comment]
Many Thanks!
