### ISSUE TITLE
Cannot read property 'login' of null error

### ISSUE THREAD

**Issue by abhisheknaiidu** [abhijithvijayan/stargazed#54]
I've been using this tool for past 2 months, but from few weeks, it's not working, I've been trying to debug things, but not able to figure it out the exact issue that's causing, would love to get it solved by you guys! Thanks! and I'm attaching the screenshot.

## Checklist
- [x] I checked that this is not an existing issue
- [x] I gave clear steps to reproduce this issue

repo - https://github.com/abhisheknaiidu/nads

<img width="1025" alt="Screenshot 2021-02-08 at 4 14 12 PM" src="https://user-images.githubusercontent.com/55599878/107209490-e0f01a80-6a28-11eb-8d90-47bb44d8024c.png">

**Comment by abhijithvijayan** [comment]
The cli github action repo has the readme correctly generated.

I will look into this issue when i get free time.
